### ISSUE TITLE
prismic sm --setup command sets up a nuxt repository and not a nextjs one when run

### ISSUE THREAD

**Issue by mrispoli24** [prismicio/prismic-cli#66]
I ran this command in a next js project and it installed all the vue dependencies from nuxt. I'm running the latest version of the CLI 3.7.11 right now. 

Doing npm install -g prismic-cli@beta fails so I think there are still things being worked out in the beta version, not sure if that is what the issue is though.

**Comment by phillysnow** [comment]
Hi @mrispoli24  You can use the `--framework` option to define your framework if the incorrect one is configured I believe.

**Comment by mrispoli24** [comment]
@phillysnow ah ok let me try that, I just did the configuration manually from what I could piece together of the repositories for nextjs.

**Comment by phillysnow** [comment]
So it should be `--framework next`

**Comment by mrispoli24** [comment]
@phillysnow any way to connect this to an existing repository?

**Comment by mrispoli24** [comment]
@phillysnow just ran prismic sm --setup --framework next and it installed the nuxt dependencies again. Makes it hard to keep testing this because I have to recreate a new repository every time.

**Comment by lihbr** [comment]
Hey @mrispoli24, thanks for trying Slice Machine and submitting this issue!

I'm really sorry to hear that you ran into those issues with Next.js and for the poor experience. I'm not sure I'm able to pinpoint it there. You can try with version `3.8.0-beta.0` if you want but I'm not 100% sure if it was fixed in this preview already.

Also to be frank we're on the eve of releasing a new version of the CLI this Wednesday (`2.8.0`), everything will be announced at our meetup: https://hopin.to/events/prismic-product-meet-up-shared-slices-slice-machine-release and this kind of issues should be fixed with it ☺️

Thanks for your patience!

**Comment by phillysnow** [comment]
Also @mrispoli24 if you don't want to set up a Prismic repo, you can specify the `--no-prismic` option like so:
`prismic sm --setup --no-prismic`

**Comment by mrispoli24** [comment]
@phillysnow thank you I ended up figuring that part out, I think maybe its been a good experience to actually have to hand set everything up anyway because now I have a better understanding of how Prismic works with next vs other headless CMS's I've used.

@lihbr I'll wait for the Wednesday release for sure to try again and see how it compares with my setup. Thanks all.

**Comment by phillysnow** [comment]
That's cool, it also gives me more impetus to create the "Configure your next project manually" article that I was thinking of :)

**Comment by mrispoli24** [comment]
@phillysnow please please do! Took a lot of repo sifting to put it all together myself... also might make it easier for us to use slice machine / contribute for other frameworks like Svelte if we can see more of how it all comes together.

**Comment by phillysnow** [comment]
This should be available on the latest beta of the CLI

**Comment by MarcMcIntosh** [comment]
should be fixed in #65
